<a href="https://colab.research.google.com/github/Camper-Lingo/CP1_SERS/blob/main/CP1_SERS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Dataset 1 — Appliances Energy Prediction  (UCI)**

Fonte: https://archive.ics.uci.edu/dataset/374/appliances+energy+prediction

**Situação**

Uma empresa de eficiência energética está analisando o comportamento de uma residência de baixo consumo. A equipe deseja identificar períodos de consumo elevado dos eletrodomésticos e observar quais condições de temperatura e umidade estavam presentes nesses momentos.

![untitled.svg]()

In [ ]:
import pandas as pd

In [39]:
df1 = pd.read_csv('/content/energydata_SAMPLE.csv')

In [ ]:
df1.head()

   Appliances  lights       T1     RH_1       T2     RH_2       T3     RH_3
0          40       0  20.8900  35.4000  17.7600  39.1633  20.2900  36.9000
1          90      10  21.8900  53.1000  21.2900  45.3600  21.6333  49.2267
2          50       0  21.3900  35.5000  17.6333  40.5300  21.6667  35.2000
3          50       0  21.3900  41.0333  23.8900  34.8400  22.0333  36.9333
4          70       0  19.9633  35.1267  16.4633  40.1267  20.0000  36.4000

In [ ]:
df1.shape

(1974, 8)

In [ ]:
print(f'Número de linhas: {df1.shape[0]}')
print(f'Número de colunas: {df1.shape[1]}')

Número de linhas: 1974
Número de colunas: 8

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Appliances  1974 non-null   int64
 1   lights      1974 non-null   int64
 2   T1          1974 non-null   float64
 3   RH_1        1974 non-null   float64
 4   T2          1974 non-null   float64
 5   RH_2        1974 non-null   float64
 6   T3          1974 non-null   float64
 7   RH_3        1974 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 123.5 KB

In [ ]:
df1.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000
mean,93.044580,3.839919,21.664703,40.219193,20.293635,40.411386,22.231615,39.209733
std,93.826149,7.937076,1.574883,3.971923,2.126958,4.037686,1.957275,3.288818
min,20.000000,0.000000,16.790000,27.733300,16.100000,24.063300,17.200000,30.133300
25%,50.000000,0.000000,20.700000,37.205825,18.790000,37.760000,20.700000,36.900000
50%,60.000000,0.000000,21.600000,39.590000,20.000000,40.433300,22.100000,38.433300
75%,100.000000,0.000000,22.600000,42.991675,21.500000,43.228325,23.290000,41.741250
max,770.000000,50.000000,26.260000,57.496700,28.917500,56.026700,29.198600,49.226700

In [ ]:
df1.columns

Index(['Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3'], dtype='object')

In [ ]:
# 2.	Renomeie Appliances para Consumo_Eletrodomesticos e simplifique
#  o nome de pelo menos três atributos ambientais.
df1.rename(columns={'Appliances': 'Consumo_Eletrodomesticos',
                    'T1': 'Temperatura_01',
                    'RH_1': 'Umidade_01'}, inplace=True)

In [ ]:
df1.head()

,Consumo_Eletrodomesticos,lights,Temperatura_01,Umidade_01,T2,RH_2,T3,RH_3
0,40,0,20.8900,35.4000,17.7600,39.1633,20.2900,36.9000
1,90,10,21.8900,53.1000,21.2900,45.3600,21.6333,49.2267
2,50,0,21.3900,35.5000,17.6333,40.5300,21.6667,35.2000
3,50,0,21.3900,41.0333,23.8900,34.8400,22.0333,36.9333
4,70,0,19.9633,35.1267,16.4633,40.1267,20.0000,36.4000

#DataSet 2 - Steel Industry Energy Consumption (UCI)

In [ ]:
import pandas as pd

dados = pd.read_csv("amostra_dataset2_steel.csv")

dados.head()

,date,Usage_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,Lagging_Current_Power_Factor,Leading_Current_Power_Factor,WeekStatus,Day_of_week,Load_Type
0,string,continuous,continuous,continuous,continuous,continuous,Weekday Weekend,Friday Monday Saturday Sunday Thursday Tuesday...,Light_Load Maximum_Load Medium_Load
1,meta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29/04/2018 07:15,2.88,3.82,0.00,60.20,100.00,Weekend,Sunday,Light_Load
3,04/10/2018 12:00,60.77,48.02,0.00,78.46,100.00,Weekday,Thursday,Maximum_Load
4,26/01/2018 11:30,120.42,59.65,0.00,89.61,100.00,Weekday,Friday,Maximum_Load

In [ ]:
dados = dados.rename(columns={
    "Usage_kWh": "Consumo_kWh",
    "Lagging_Current_Power_Factor": "FP_Atraso",
    "Leading_Current_Power_Factor": "FP_Avanco"
})

dados.head()

,date,Consumo_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,FP_Atraso,FP_Avanco,WeekStatus,Day_of_week,Load_Type
0,string,continuous,continuous,continuous,continuous,continuous,Weekday Weekend,Friday Monday Saturday Sunday Thursday Tuesday...,Light_Load Maximum_Load Medium_Load
1,meta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,29/04/2018 07:15,2.88,3.82,0.00,60.20,100.00,Weekend,Sunday,Light_Load
3,04/10/2018 12:00,60.77,48.02,0.00,78.46,100.00,Weekday,Thursday,Maximum_Load
4,26/01/2018 11:30,120.42,59.65,0.00,89.61,100.00,Weekday,Friday,Maximum_Load

In [ ]:
print(dados.shape)
dados.info()
dados.describe()

(7010, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7010 entries, 0 to 7009
Data columns (total 9 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   date                                  7010 non-null   object
 1   Consumo_kWh                           7009 non-null   object
 2   Lagging_Current_Reactive.Power_kVarh  7009 non-null   object
 3   Leading_Current_Reactive_Power_kVarh  7009 non-null   object
 4   FP_Atraso                             7009 non-null   object
 5   FP_Avanco                             7009 non-null   object
 6   WeekStatus                            7009 non-null   object
 7   Day_of_week                           7009 non-null   object
 8   Load_Type                             7009 non-null   object
dtypes: object(9)
memory usage: 493.0+ KB

,date,Consumo_kWh,Lagging_Current_Reactive.Power_kVarh,Leading_Current_Reactive_Power_kVarh,FP_Atraso,FP_Avanco,WeekStatus,Day_of_week,Load_Type
count,7010,7009,7009,7009,7009,7009,7009,7009,7009
unique,7010,1900,1396,639,3059,1307,3,8,4
top,14/04/2018 10:30,2.92,0.00,0.00,100.00,100.00,Weekday,Thursday,Light_Load
freq,1,135,1420,4711,1472,4886,5026,1048,3572

# Dataset 3 — Power Consumption of Tetouan City (UCI)

Fonte: https://archive.ics.uci.edu/dataset/849/power+consumption+of+tetouan+city

Situação:

Uma equipe responsável pelo planejamento da distribuição de energia em Tétouan deseja identificar qual das três zonas apresenta o maior pico de consumo e observar as condições ambientais registradas nos momentos de maior demanda

In [ ]:
df3 = pd.read_csv('/content/Tetuan City power consumption.csv')

In [ ]:
df3.columns

Index(['Temperature', 'Humidity', 'Wind Speed'], dtype='object')

In [31]:
#Renomeie as três variáveis de consumo para Consumo_Zona_1, Consumo_Zona_2 e Consumo_Zona_3

df3 = df3.rename(columns={
    'Temperature': 'Consumo_Zona_1',
    'Humidity': 'Consumo_Zona_2',
    'Wind Speed': 'Consumo_Zona_3'
})

In [30]:
#Determine o consumo máximo registrado em cada uma das três zonas.

df3['Consumo_Zona_1'] = pd.to_numeric(df3['Consumo_Zona_1'], errors='coerce')
df3['Consumo_Zona_2'] = pd.to_numeric(df3['Consumo_Zona_2'], errors='coerce')
df3['Consumo_Zona_3'] = pd.to_numeric(df3['Consumo_Zona_3'], errors='coerce')


maximos = df3[['Consumo_Zona_1', 'Consumo_Zona_2', 'Consumo_Zona_3']].max()
print(maximos)
#Identifique qual zona apresenta o maior pico de consumo na amostra.
zona_maior_pico = maximos.idxmax()
maior_pico = maximos.max()

print("Zona com maior pico:", zona_maior_pico)
print("Valor do maior pico:", maior_pico)
#Para a zona identificada, calcule 70% do valor máximo e crie um DataFrame com os registros acima desse limiar.
valor_maximo = df3[zona_maior_pico].max()
limiar = 0.70 * valor_maximo
df_acima_limiar = df3[df3[zona_maior_pico] > limiar]

print("Limiar (70%):", limiar)
print(df_acima_limiar)

Consumo_Zona_1    39.600
Consumo_Zona_2    94.700
Consumo_Zona_3     4.998
dtype: float64
Zona com maior pico: Consumo_Zona_2
Valor do maior pico: 94.7
Limiar (70%): 66.28999999999999
      Consumo_Zona_1  Consumo_Zona_2  Consumo_Zona_3
5              12.42           72.30           0.081
6              14.58           80.60           0.080
7              14.99           69.14           0.074
8              11.16           70.80           0.080
9              19.21           89.40           4.923
...              ...             ...             ...
5236           16.34           82.30           0.069
5237           17.20           80.10           4.909
5240           16.93           76.10           0.082
5241           10.93           67.88           0.082
5243           16.99           83.00           0.081

[3095 rows x 3 columns]

In [32]:
#Conte os registros e calcule o percentual que eles representam.

# Conta os registros acima do limiar
quantidade = len(df_acima_limiar)

# Calcula o percentual em relação ao total da amostra
percentual = (quantidade / len(df3)) * 100

print("Quantidade de registros:", quantidade)
print("Percentual:", percentual, "%")

Quantidade de registros: 3095
Percentual: 59.019832189168575 %

In [37]:
#Calcule a temperatura média e crie um segundo DataFrame contendo consumo acima do limiar e temperatura acima da média.

# Calcula a temperatura média
temperatura_media = df3['Consumo_Zona_1'].mean()

# Cria o DataFrame com as duas condições
df_acima_limiar_temperatura = df3[
    (df3[zona_maior_pico] > limiar) &
    (df3['Consumo_Zona_1'] > temperatura_media)
]

print("Temperatura média:", temperatura_media)
print(df_acima_limiar_temperatura)

Temperatura média: 18.855991606257156
      Consumo_Zona_1  Consumo_Zona_2  Consumo_Zona_3
9              19.21           89.40           4.923
14             21.03           86.50           0.068
27             26.92           70.20           4.909
29             25.37           77.80           4.918
31             24.60           91.30           4.918
...              ...             ...             ...
5215           26.22           82.50           4.916
5228           25.35           82.30           4.914
5230           18.88           87.60           4.917
5233           26.36           76.30           4.920
5235           21.89           68.49           4.913

[1251 rows x 3 columns]

In [38]:
#Compare os dois conjuntos e explique o que ocorreu com a quantidade de registros após a inclusão da condição ambiental.

# Quantidade antes da condição de temperatura
qtd_antes = len(df_acima_limiar)

# Quantidade depois de adicionar a condição de temperatura
qtd_depois = len(df_acima_limiar_temperatura)

# Diferença
diferenca = qtd_antes - qtd_depois

# Percentual de redução
percentual_reducao = (diferenca / qtd_antes) * 100

print("Registros antes:", qtd_antes)
print("Registros depois:", qtd_depois)
print("Registros removidos:", diferenca)
print(f"Redução: {percentual_reducao:.2f}%")

Registros antes: 3095
Registros depois: 1251
Registros removidos: 1844
Redução: 59.58%

#Dataset 6 — Individual Household Electric Power Consumption (UCI)

Situação

Uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de demanda elevada que também apresentem corrente acima do comportamento médio. O dataset é o mesmo utilizado como referência em aula, mas o critério de análise será diferente.